### ISSUE TITLE
Decorator and decorated only works with jsp extension

### ISSUE THREAD

**Issue by jairojunior** [sitemesh/sitemesh3#68]
Using a webapp similar to sitemesh-examples-hellowebapp in tomcat 8.0.12. 

Sitemesh only works when used with jsp extension for both decorator and decorated in this tomcat version, but in tomcat 7.0.55 it works just fine with html extesion.

When used with html extension, the final page document is incomplete. Not sure if it's sitemesh or tomcat bug.

**Comment by codeconsole** [comment]
Is this fixed now? I attempted to get Tomcat 8 working with the example app, but the Tomcat 8 gradle plugin does not start up.  It seems highly unstable and unsupported at this point.

Tomcat 7 gradle plugin works fine.

https://github.com/bmuschko/gradle-tomcat-plugin

**Comment by gstandaert** [comment]
It is not fixed yet. The problem still occurs with sitemesh-3.0.1 on wildfly-8.2.0.Final.

If I switch form static *.html files to *.jsp files (for both the content files AND the decorators), it is working as expected.

**Comment by DanneLeung** [comment]
It not fixed yet. In my case, the problem occurs with sitemesh decorating static html that responses from springmvc resource handler. Root cause is the response content-length set as the origin html size in ResourceHttpRequestHandler, and sitemesh filter not check and reset. I add another filter before sitemesh filter to fix this issue, it work well with Tomcat8 and Spring 4.1.x.

**Comment by gmihaylov840** [comment]
Still an issue with Jetty 9.2.11.v20150529 and Sitemesh 3. I have the same setup as DanneLeung mentioned.

**Comment by viruscamp** [comment]
The spring-mvc static resources Processor will set Content-Length while writing datas
And the spring-mvc controller does not set Content-Length

SiteMesh3 do not change Content-Length , but writes more datas to Response , then cause the content truncated.

We should change method below:
```java
org.sitemesh.webapp.SiteMeshFilter
protected boolean postProcess(String contentType, CharBuffer buffer,
                                  HttpServletRequest request, HttpServletResponse response,
                                  ResponseMetaData metaData)

// the method writeValueTo should return the length of bytes written
int written = content.getData().writeValueTo(response.getWriter());

// if the original response has Content-Length , then set it with new value
if (response.containsHeader("Content-Length")) {
    response.setContentLength(written);
}
```

**Comment by sgreenholtz** [comment]
I am still finding this error with both Tomcat 8 and Tomcat 8.5.
